services:
  - type: web
    name: django-app
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn DJANGO-REAL-ESTATE-MANAGEMENT-WEBAPP.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: coralcity.settings