services:
  - type: web
    name: django-app
    runtime: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py migrate
      python manage.py collectstatic --no-input
    startCommand: gunicorn DJANGO-REAL-ESTATE-MANAGEMENT-WEBAPP.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: coralcity.settings
